providers = ["node"]

[variables]
NODE_VERSION = "18"
NPM_CONFIG_PRODUCTION = "false"
NODE_ENV = "production"

[phases.build]
cmds = [
  "npm ci",
  "npm run build"
]

[phases.deploy]
cmd = "npm run preview"